apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: herman-hkedevopstest
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: herman-hkedevopstest
    spec:
      containers:
      - name: herman-hkedevopstest-2
        image: docker.io/pleungdev/herman-hkedevopstest:$BUILD_ID
        ports:
        - containerPort: 41085
---
apiVersion: v1
kind: Service
metadata:
  name: herman-hkedevopstest
spec:
  type: LoadBalancer
  ports:
  - port: 41085
  selector:
    app: herman-hkedevopstest
