apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hkedevopstest
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: hkedevopstest
    spec:
      containers:
      - name: hkedevopstest
        image: hermanacr.azurecr.io/hermanbuaton/hkedevopstest:$BUILD_ID
        ports:
        - containerPort: 41085
---
apiVersion: v1
kind: Service
metadata:
  name: hkedevopstest
spec:
  type: LoadBalancer
  ports:
  - port: 41085
  selector:
    app: hkedevopstest
